### ISSUE TITLE
Build fails at pdf file creation (calibre problem)

### ISSUE THREAD

**Issue by gavvvr** [basarat/typescript-book#641]
```
Creating PDF Output...
67% Running PDF Output plugin
68% Parsed all content for markup transformation
70% Completed markup transformation
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runner'
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Traceback (most recent call last):
  File "/usr/bin/ebook-convert", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 401, in main
    plumber.run()
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1274, in run
    self.output_plugin.convert(self.oeb, self.output, self.input_plugin,
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 188, in convert
    self.convert_text(oeb_book)
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/pdf_output.py", line 253, in convert_text
    convert(
  File "/usr/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 1195, in convert
    manager = RenderManager(opts, log, container.root)
  File "/usr/lib/calibre/calibre/ebooks/pdf/html_writer.py", line 279, in __init__
    ans.setUrlRequestInterceptor(self.interceptor)
AttributeError: 'QWebEngineProfile' object has no attribute 'setUrlRequestInterceptor'
```

**Comment by fortezhuo** [comment]
friendly ping @basarat . please help. we can't download pdf / epub / mobi since build failed

**Comment by Nikurasukun** [comment]
Yeah, please merge it ^^

**Comment by mushifali** [comment]
Thanks, @fortezhuo for the fix. I was able to generate the ebooks. You can find them here: 

https://github.com/mushifali/typescript-book/actions/runs/3914977395
